name: CI pipeline

on: [push]

jobs:
  build:
    runs-on: windows-2016
    env:
      ERE_DIRECTORY_WATCHER_DIR: watch-pdf
      ERE_TITUS_CONNECTOR_TLS_CERT_TRUST_STORE_DIR: ${{ github.workspace }}\\src\\test\\resources\\certs
      ERE_TITUS_CONNECTOR_TLS_CERT_TRUST_STORE_PWD: "00"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn -B verify