name: CI pipeline

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ERE_DIRECTORY_WATCHER_DIR: watch-pdf
      ERE_TITUS_CONNECTOR_TLS_CERT_TRUST_STORE_DIR: env.GITHUB_WORKSPACE/ere-ps-app/src/test/resources/certs
      ERE_TITUS_CONNECTOR_TLS_CERT_TRUST_STORE_PWD: password

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B verify
      - name: Spotbugs
        run: mvn -B verify spotbugs:spotbugs
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'
      - name: PMD
        run: mvn -B verify pmd:pmd
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/pmd.xml'
